name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build shared package
      run: |
        cd packages/shared
        npm run build

    - name: Build drawing tool
      run: |
        cd packages/drawing-tool
        npm run build

    - name: Build tour component
      run: |
        cd packages/tour-component
        npm run build

    - name: Build tour component demo
      run: |
        cd packages/tour-component/demo
        npm ci
        npm run build

    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4

    - name: Prepare deployment
      if: github.ref == 'refs/heads/main'
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy drawing tool (main site)
        cp -r packages/drawing-tool/dist/* deploy/
        
        # Copy tour component demo (sub-directory)
        mkdir -p deploy/tour-player
        cp -r packages/tour-component/demo/dist/* deploy/tour-player/
        
        # Create index.html redirect if needed
        if [ ! -f deploy/index.html ]; then
          cat > deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Site Tour Tools</title>
          <meta http-equiv="refresh" content="0; url=./drawing-tool/">
        </head>
        <body>
          <p>Redirecting to <a href="./drawing-tool/">Site Tour Tools</a>...</p>
        </body>
        </html>
        EOF
        fi

    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: deploy

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4